


!Ficha methodsFor: 'all' stamp: 'GRUPO5 10/27/2021 09:09'!
    saltar_arriba
    "mueve la ficha dos posiciones arriba"
    eliminar_debajo
    .! !

!Ficha methodsFor: 'all' stamp: 'GRUPO5 10/27/2021 09:09'!
    saltar_abajo
    "mueve la ficha dos posiciones abajo"
    eliminar_arriba
    .! !

!Ficha methodsFor: 'all' stamp: 'GRUPO5 10/27/2021 09:09'!
    saltar_izq
    "mueve la ficha dos posiciones a la izquierda"
    eliminar_der
    .! !

!Ficha methodsFor: 'all' stamp: 'GRUPO5 10/27/2021 09:09'!
    saltar_der   
    "mueve la ficha dos posiciones a la derecha"
    eliminar_izq
    .! !